name: birbs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - future
  - setuptools
  - attrs
  - typing
  - typing-extensions
  - requests
  - numpy
  - opencv=4.6.0
  - pandas=1.4.3
  - asyncpg=0.26.0
  - psycopg2-binary=2.9.3
  - sqlalchemy=1.4.39
  - fastapi=0.79.0
  - fastapi_users=10.1.1
  - fastapi-users-db-sqlalchemy=4.0.3
  - jinja2=3.1.2
  - uvicorn=0.18.2
  - aiofiles=0.8.0
  - asyncio=1.5.5
  - python-dotenv=0.20.0
  - aiogram=2.20
  - aiosignal=1.2.0
  - pytz=2022.1
  - uvloop=0.16.0
  - certifi=2022.6.15
  - async-timeout=4.0.2
  - aiohttp=3.8.1
  - pip
  - pip:
    - databases[postgresql]
    - python-periphery
    - python-telegram-bot==13.13