version: '3.5'

services:
  api:
    container_name: birbs
    image: birbs:api
    build:
      context: ..
      dockerfile: docker/api/Dockerfile
    environment:
      API_UVICORN_PROCESSES: ${API_UVICORN_PROCESSES}
      API_WEB_PORT: ${API_WEB_PORT}
      API_SECRET: ${API_SECRET}
      API_ADMIN_EMAIL: ${API_ADMIN_EMAIL}
      API_ADMIN_PASSWORD: ${API_ADMIN_PASSWORD}
      API_TELEGRAM_TOKEN: ${API_TELEGRAM_TOKEN}

      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      UID: ${UID}
    user: "${UID}:${GID}"
    stdin_open: true
    tty: true
    ports:
      - "8888:8888"
      - "${API_WEB_PORT}:8080"
      - "${API_SSH_PORT}:22"
    volumes:
      - ./:/home/user/birbs
      - /lib/modules:/lib/modules
      - /sys:/sys
    cap_add:
      - ALL
    devices:
      - /dev/mem:/dev/mem
      - /dev/ttyAMA0:/dev/ttyAMA0
    networks:
      - postgres
    restart: always

#  postgres:
#    container_name: bird_postgres_container
#    image: postgres:13
#    environment:
#      POSTGRES_USER: ${POSTGRES_USER}
#      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#      PGDATA: /data/postgres
#    volumes:
#       - ./postgres:/data/postgres
#    ports:
#      - "${POSTGRES_PORT}:5432"
#    networks:
#      - postgres
#    restart: always
#
#  pgadmin:
#    container_name: bird_pgadmin_container
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
#      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#       - ./pgadmin:/root/.pgadmin
#
#    ports:
#      - "${PGADMIN_PORT}:80"
#    networks:
#      - postgres
#    restart: always

networks:
  postgres:
    driver: bridge

# UID="$(id -u)" GID="$(id -g)" docker-compose up