
# commands
COMMAND_LEDS_GET = 0x10
COMMAND_LEDS_STATUS_SET = 0x11
COMMAND_LEDS_VALUE_SET = 0x12

COMMAND_FEEDER_GET_SERVO_ANGLE = 0x20
COMMAND_FEEDER_BOX_GET_SERVO_OPEN_CLOSE_ANGLES = 0x21
COMMAND_FEEDER_BOX_SET_SERVO_OPEN_CLOSE_ANGLES = 0x22
COMMAND_FEEDER_GATE_GET_SERVO_OPEN_CLOSE_ANGLES = 0x23
COMMAND_FEEDER_GATE_SET_SERVO_OPEN_CLOSE_ANGLES = 0x24

COMMAND_FEEDER_BOX_OPEN = 0x25
COMMAND_FEEDER_BOX_CLOSE = 0x26
COMMAND_FEEDER_BOX_SET_ANGLE = 0x27

COMMAND_FEEDER_GATE_FEED = 0x28
COMMAND_FEEDER_GATE_FEED_MS = 0x29
COMMAND_FEEDER_GATE_SET_ANGLE = 0x2A
COMMAND_FEEDER_GATE_OPEN = 0x2B
COMMAND_FEEDER_GATE_CLOSE = 0x2C

COMMAND_DRINKER_GET_PARAMS = 0x30
COMMAND_DRINKER_INPUT_GET_OPEN_CLOSE_ANGLES = 0x31
COMMAND_DRINKER_INPUT_SET_OPEN_CLOSE_ANGLES = 0x32
COMMAND_DRINKER_OUTPUT_GET_OPEN_CLOSE_ANGLES = 0x33
COMMAND_DRINKER_OUTPUT_SET_OPEN_CLOSE_ANGLES = 0x34
COMMAND_DRINKER_WATER_LEVEL_GET_PARAMS = 0x35
COMMAND_DRINKER_WATER_LEVEL_SET_PARAMS = 0x36
COMMAND_DRINKER_WATER_LEVEL_GET_CURRENT = 0x37
COMMAND_DRINKER_INPUT_OPEN = 0x38
COMMAND_DRINKER_INPUT_CLOSE = 0x39
COMMAND_DRINKER_INPUT_SET_ANGLE = 0x3A
COMMAND_DRINKER_OUTPUT_OPEN = 0x3B
COMMAND_DRINKER_OUTPUT_CLOSE = 0x3C
COMMAND_DRINKER_OUTPUT_SET_ANGLE = 0x3D
COMMAND_DRINKER_FILL = 0x3E
COMMAND_DRINKER_EMPTY = 0x3F
COMMAND_DRINKER_RESET = 0x40

# command responce
COMMAND_RESPONSE_SELECT_SUCCESS = 0x69
COMMAND_RESPONSE_SELECT_ERROR = 0x70
COMMAND_RESPONSE_ARGUMENT_SUCCESS = 0x40
COMMAND_RESPONSE_ARGUMENT_ERROR = 0x41
COMMAND_RESPONSE_PROCESSING_SUCCESS = 0xAA
COMMAND_RESPONSE_PROCESSING_ERROR = 0xAB
COMMAND_RESPONSE_RESPONSE_ERROR = 0x54